---
- name: ansible project
  hosts: prod
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  tasks:
   - name: war file
     copy:
       src: target/wwp-1.0.0.war
       dest: /var/lib/tomcat9/webapps/target/wwp-1.0.0.war
       owner: tomcat9
       group: tomcat9
